<?php 
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_58b1726a6b56d',
	'title' => 'Theme Options',
	'fields' => array(
		array(
			'key' => 'field_58b175abef2cf',
			'label' => 'General',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5a32ab165107b',
			'label' => 'Skin Color',
			'name' => 'skin_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#f3759a',
		),	
		array(
			'key' => 'field_5a8dc24e2cd02',
			'label' => 'Action Button Color',
			'name' => 'action_button_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),			
		array(
			'key' => 'field_5a5a9e50d3537',
			'label' => 'Logo type',
			'name' => 'logo_type',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'imagel' => 'Image Logo',
				'textl' => 'Text Logo',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_58b175e0ef2d0',
			'label' => 'Logo',
			'name' => 'logo',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5a5a9e50d3537',
						'operator' => '==',
						'value' => 'imagel',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_58b17625ef2d1',
			'label' => 'Sticky Logo',
			'name' => 'sticky_logo',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5a5a9e50d3537',
						'operator' => '==',
						'value' => 'imagel',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5a5a9f63fe3e3',
			'label' => 'Logo Text',
			'name' => 'logo_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5a5a9e50d3537',
						'operator' => '==',
						'value' => 'textl',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Logo',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5a738efa16828',
			'label' => 'Logo Font Size',
			'name' => 'logo_font_size',
			'type' => 'range',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5a5a9e50d3537',
						'operator' => '==',
						'value' => 'textl',
					),
				),
			),
			'wrapper' => array(
				'width' => '60',
				'class' => '',
				'id' => '',
			),
			'default_value' => 50,
			'min' => 30,
			'max' => 100,
			'step' => 2,
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_5a73984dfffef',
			'label' => 'Logo Color',
			'name' => 'logo_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5a5a9e50d3537',
						'operator' => '==',
						'value' => 'textl',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_58b1c90400368',
			'label' => 'Favicon',
			'name' => 'favicon',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5a738e6816824',
			'label' => 'Typography',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => 'm_st',
				'id' => '',
			),
			'message' => '',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_5aac40423a415',
			'label' => 'Menu Font Family',
			'name' => 'menu_font_family',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Open Sans' => 'Open Sans',
				'Roboto' => 'Roboto',
				'Titillium Web' => 'Titillium Web',
				'Gotham' => 'Gotham',
			),
			'default_value' => array(
				0 => 'Titillium Web',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),		
		array(
			'key' => 'field_5a738ec616825',
			'label' => 'Logo Font Family',
			'name' => 'logo_font_family',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Titillium Web' => 'Titillium Web',
				'Open Sans' => 'Open Sans',
				'Roboto' => 'Roboto',
				'Gotham' => 'Gotham',
				'Coolvetica' => 'Coolvetica',
			),
			'default_value' => array(
				0 => 'Gotham',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5a8dc24f2cd03',
			'label' => 'Body Text Font Family',
			'name' => 'body_text_font_family',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Open Sans' => 'Open Sans',
				'Roboto' => 'Roboto',
				'Titillium Web' => 'Titillium Web',
				'Gotham' => 'Gotham',
			),
			'default_value' => array(
				0 => 'Gotham',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),		
		array(
			'key' => 'field_5a739d29ffff0',
			'label' => 'H1 Font Family',
			'name' => 'h1_font_family',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Titillium Web' => 'Titillium Web',
				'Open Sans' => 'Open Sans',
				'Roboto' => 'Roboto',
				'Gotham' => 'Gotham',
				'Coolvetica' => 'Coolvetica',
			),
			'default_value' => array(
				0 => 'Coolvetica',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5a739d46ffff1',
			'label' => 'H2 Font Family',
			'name' => 'h2_font_family',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Titillium Web' => 'Titillium Web',
				'Open Sans' => 'Open Sans',
				'Roboto' => 'Roboto',
				'Gotham' => 'Gotham',
				'Coolvetica' => 'Coolvetica',
			),
			'default_value' => array(
				0 => 'Coolvetica',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5a739d5bffff2',
			'label' => 'Action Button Font Family',
			'name' => 'action_button_font_family',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Titillium Web' => 'Titillium Web',
				'Open Sans' => 'Open Sans',
				'Roboto' => 'Roboto',
				'Gotham' => 'Gotham',
			),
			'default_value' => array(
				0 => 'Gotham',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5a477a6c44726',
			'label' => 'Header',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5a381cbe0a5c5',
			'label' => 'Header Style',
			'name' => 'header_style',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '42',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'style1' => 'Logo Left Menu Right',
				'style2' => 'Logo Up Menu Down',
			),
			'allow_null' => 0,
			'default_value' => 'style1',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_5a3847e65694b',
			'label' => 'Menu BG color',
			'name' => 'menu_background_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5a384fa41c6da',
			'label' => 'Menu color',
			'name' => 'menu_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '19',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5aac29c24333e',
			'label' => 'Hover Color',
			'name' => 'hover_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '19',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#9b59b6',
		),	
							array(
								'key' => 'field_5a738e6816833',
								'label' => 'Top Slider Setting',
								'name' => '',
								'type' => 'message',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => 'm_st',
									'id' => '',
								),
								'message' => '',
								'new_lines' => 'wpautop',
								'esc_html' => 0,
							),		
                                array(
                                    'key' => 'field_5b70298ba5777',
                                    'label' => 'Delay time of slide (sec)',
                                    'name' => 'delay_time',
                                    'type' => 'range',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '50',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'min' => 1,
                                    'max' => 10,
                                    'step' => 1,
                                    'prepend' => '',
                                    'append' => '',
                                ),
                                array(
                                    'key' => 'field_5b702ac9a5788',
                                    'label' => 'Slide Speed (m sec)',
                                    'name' => 'slide_speed2',
                                    'type' => 'range',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '50',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'min' => 100,
                                    'max' => 2000,
                                    'step' => 100,
                                    'prepend' => '',
                                    'append' => '',
                                ), 
		array(
			'key' => 'field_5a738e6816881',
			'label' => 'Page Title Show on Inner pages',
			'name' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => 'm_st',
				'id' => '',
			),
			'message' => '',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),                                

                array(
                    'key' => 'field_5b4e9af040c8c',
                    'label' => 'Hide Title',
                    'name' => 'page_title',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 1,
                    'ui' => 1,
                    'ui_on_text' => 'Show Title',
                    'ui_off_text' => 'Hide Title',
                ), 		                                		
		array(
			'key' => 'field_58b1765fef2d2',
			'label' => 'Footer',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5a736e70af1d6',
			'label' => 'Background Color',
			'name' => 'f_bgcolor',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5a73842de4481',
			'label' => 'Footer text color',
			'name' => 'footer_text_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_58b17673ef2d3',
			'label' => 'Copyright text',
			'name' => 'copyright_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Copyright 2016. _______ All right Reserved',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_598c1d63ddb99',
			'label' => 'Logo of Footer',
			'name' => 'logo_f',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'noimage' => 'No Footer Logo',
				'imagel' => 'Image Logo',
				'textl' => 'Text Logo',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_598c1f66ddb9a',
			'label' => 'Image Logo',
			'name' => 'image_logo',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_598c1d63ddb99',
						'operator' => '==',
						'value' => 'imagel',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_598c1fcaddb9b',
			'label' => 'Text Logo',
			'name' => 'text_logo',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_598c1d63ddb99',
						'operator' => '==',
						'value' => 'textl',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_5aac33097d6e3',
			'label' => 'Logo Color',
			'name' => 'f_logo_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_598c1d63ddb99',
						'operator' => '==',
						'value' => 'textl',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5b0867a4465d3',
			'label' => 'Padding Top',
			'name' => 'footer_padding',
			'type' => 'range',
			'instructions' => 'Footer Padding Increase/Decrease',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 30,
			'min' => 10,
			'max' => 150,
			'step' => 5,
			'prepend' => '',
			'append' => '',
		),		
		array(
			'key' => 'field_5b0867b446511',
			'label' => 'Padding Bottom',
			'name' => 'footer_padding_bt',
			'type' => 'range',
			'instructions' => 'Footer Padding Increase/Decrease',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => 30,
			'min' => 10,
			'max' => 150,
			'step' => 5,
			'prepend' => '',
			'append' => '',
		),		
		array(
			'key' => 'field_58b1ad00b6bf2',
			'label' => 'SEO',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_58b1ad22b6bf3',
			'label' => 'Keywords',
			'name' => 'keywords',
			'type' => 'textarea',
			'instructions' => 'Place you keywords here',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 4,
			'new_lines' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_58b1ad7fb6bf4',
			'label' => 'Description',
			'name' => 'description',
			'type' => 'textarea',
			'instructions' => 'Place your description here.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 4,
			'new_lines' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_598a23a08ca33',
			'label' => 'Blog',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_598a23b78ca34',
			'label' => 'Length of post title',
			'name' => 'length_blog',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 10,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_598a24458ca35',
			'label' => 'Read more',
			'name' => 'read_more',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Read more',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5a7376f798487',
			'label' => 'Contact',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5a73771298488',
			'label' => 'Contact Form Admin Email',
			'name' => 'mail_contact_form',
			'type' => 'email',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'shaid1985@gmail.com',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_5a8dfdfac62d9',
			'label' => 'Submit Button Color',
			'name' => 'submit_button_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),	
		
		array(
			'key' => 'field_5a3822f0b5eca',
			'label' => 'Custom Css',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5a38235eb5ecb',
			'label' => 'Custom Css',
			'name' => 'custom_css',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '.col-12.bigtitle {
    margin-top: 120px;
    margin-left: 500px;
}',
			'placeholder' => 'Put Custom Css here',
			'maxlength' => '',
			'rows' => 12,
			'new_lines' => '',
		), 
		array(
			'key' => 'field_5b2d33aa27619',
			'label' => 'Facebook Pixel',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5b2d33ff2761a',
			'label' => 'Facebook Pixel Code',
			'name' => 'custom_js',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Insert Code Here',
			'maxlength' => '',
			'rows' => 12,
			'new_lines' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;